language: python
python:
  - 2.7
  - pypy
install:
  - pip install setuptools
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python setup.py test
  - PYTHONPATH=. coverage run --source gviewer gviewer/tests/run_tests.py
after_success:
    coveralls
