language: python
python:
  - 2.7
  - pypy
install:
  - pip install setuptools
  - pip install -r requirements.txt
  - pip install coverage coveralls
script:
  - python setup.py test
  - coverage run --source=gviewer -m unittest discover
after_success:
    coveralls
